'use client'

import { usePreferences } from '@/components/SitePreferences'
import { useCallback } from 'react'

// Source copy is kept alongside its English equivalent so the project modules
// use the same locale preference without modifying data keys or research files.
export const projectCopy: Record<string, string> = {
  'Airbnb — Ciudad de México': 'Airbnb — Mexico City',
  'Olist — comercio electrónico': 'Olist — e-commerce',
  'Reservas y siniestralidad': 'Reserves and claims performance',
  'Casa/depto completo': 'Entire home/apartment',
  'Categoría': 'Category',
  'Año inicial': 'Start year',
  'Año final': 'End year',
  'Línea de negocio': 'Line of business',
  'Compañía': 'Insurer',
  'Tarjeta de crédito': 'Credit card',
  'Tarjeta de débito': 'Debit card',
  'Boleto bancario': 'Bank slip',
  'Vale': 'Voucher',
  'Sin especificar': 'Unspecified',
  '04 — RFM y LTV': '04 — RFM and LTV',
  'Longitud': 'Longitude',
  'Latitud': 'Latitude',
  'Segmento': 'Segment',
  'Anfitriones': 'Hosts',
  'Ofertas': 'Listings',
  'Precio prom./noche': 'Avg. nightly price',
  'Precio (MXN/noche)': 'Price (MXN/night)',
  'Listo': 'Ready',
  'Iniciando servidor': 'Starting data service',
  'Cargando datos': 'Loading data',
  'El servidor estuvo inactivo. Esperando que arranque...': 'The data service was idle. Waiting for it to start…',
  'Calificacion:': 'Rating:',
  'Entregas tardias:': 'Late deliveries:',
  'Calificacion promedio': 'Average rating',
  '% entregas tardias': '% late deliveries',
  'Valor promedio': 'Average value',
  'Calificacion': 'Rating',
  'Alto valor recurrente': 'High-value repeat buyers',
  'Recurrentes estables': 'Stable repeat buyers',
  'Compra reciente': 'Recent buyers',
  'Valor': 'Value',
  'Severidad': 'Severity',
  'Severidad promedio': 'Average severity',
  'Observado': 'Observed',
  'Reportado': 'Reported',
  'Último (Ultimate)': 'Ultimate',
  'Incurrido': 'Incurred',
  'Pagado': 'Paid',
  'Entrega': 'Delivery',
  'Recompra': 'Repeat purchase',
  'Promedio': 'Average',
  'Mejor ·': 'Best ·',
  'Peor ·': 'Worst ·',
  'Potencial Leal': 'Potentially loyal',
  'Inactivos': 'Inactive',
  'Otros': 'Other',
  '% de los clientes': '% of customers',
  'Ingresos acumulados': 'Cumulative revenue',
  'Igualdad perfecta': 'Perfect equality',
  '20% superior =': 'Top 20% =',
  '% de los ingresos': '% of revenue',
  'Pico ·': 'Peak ·',
  'Clientes nuevos': 'New customers',
  'Estados cubiertos': 'States covered',
  'con 100+ clientes': 'with 100+ customers',
  'Mejor estado': 'Best state',
  'estados': 'states',
  'Ticket medio': 'Average order value',
  'Un punto por estado, área proporcional al número de clientes · r =': 'One point per state, area proportional to customers · r =',
  'Índice': 'Contents',
  'Limitaciones': 'Limitations',
  'R — Recencia': 'R — Recency',
  'Menor es mejor': 'Lower is better',
  'F — Frecuencia': 'F — Frequency',
  'Mayor es mejor': 'Higher is better',
  'M — Monto': 'M — Monetary value',
  'Supervivencia Kaplan-Meier': 'Kaplan–Meier survival',
  'En este contexto': 'In this context',
  'Pedidos entregados': 'Delivered orders',
  'Estados': 'States',
  'Cohortes y supervivencia': 'Cohorts and survival',
  'Etapa': 'Stage',
  'Por clientes': 'By customers',
  'Por ingresos': 'By revenue',
  'Mapa de calor de retención — por': 'Retention heatmap — by',
  'Porcentaje de': 'Percentage of',
  'de cada cohorte que reaparece en cada mes posterior': 'from each cohort returning in subsequent months',
  'Comparar': 'Compare',
  'Mejor vs peor': 'Best versus worst',
  'Cohortes elegidas (': 'Selected cohorts (',
  'Mejor contra peor cohorte': 'Best versus worst cohort',
  'Cohortes elegidas': 'Selected cohorts',
  'Hasta': 'Up to',
  'cohortes contra el promedio': 'cohorts compared with the average',
  'Sin segmentar': 'All customers',
  'Segmentos visibles': 'Visible segments',
  'de 7': 'of 7',
  '% base': '% of customers',
  'Curva de Lorenz sobre los': 'Lorenz curve across',
  'clientes · Gini': 'customers · Gini',
  '% clientes': '% customers',
  '% ingresos': '% revenue',
  'Mapa RFM': 'RFM map',
  'Recencia media': 'Average recency',
  'Pedidos medios': 'Average orders',
  'Ingreso medio': 'Average revenue',
  'días': 'days',
  'Mediana nacional': 'National median',
  'ingresos': 'revenue',
  'Casual (1 listado)': 'Casual (one listing)',
  'Profesional (2-5 listados)': 'Professional (2–5 listings)',
  'Empresarial (6+ listados)': 'Business (6+ listings)',
  'Pago: vale': 'Payment: voucher',
  ' · no concluyente': ' · inconclusive',
  'Portafolio': 'Portfolio',
  'Caso de Estudio 01 — Marzo 2026': 'Case study · March 2026',
  'Caso de Estudio 02 — Marzo 2026': 'Case study · March 2026',
  'Caso de Estudio 01 -- Marzo 2026': 'Case study · March 2026',
  'Ciudad de México': 'Mexico City',
  'E-Commerce Brasil': 'Brazilian e-commerce',
  'Reservas y': 'Reserves and',
  'Siniestralidad': 'Claims performance',
  'Inside Airbnb recopila datos públicos de listados de Airbnb en ciudades de todo el mundo. Este dashboard analiza más de 27,000 ofertas activas en la Ciudad de México — precios por noche, concentración por alcaldía y patrones de anfitriones — para entender la dinámica del alojamiento a corto plazo en una de las ciudades más visitadas de América Latina.': 'Explore more than 27,000 Mexico City listings using public Inside Airbnb data: nightly prices, borough concentration, and host portfolios reveal the structure of the short-term rental market.',
  'Snapshot de marzo 2025': 'March 2025 snapshot',
  '27,051 listados activos con 79 variables cada uno': '27,051 active listings with 79 variables each',
  'Inside Airbnb es un proyecto independiente que extrae datos públicos de la plataforma Airbnb para hacer transparente el impacto del alquiler a corto plazo en las ciudades. Los datos incluyen precio por noche, ubicación, tipo de alojamiento, calificaciones, disponibilidad y perfil del anfitrión.': 'Inside Airbnb independently collects public listing data to make the impact of short-term rentals visible. Fields include nightly prices, location, room type, ratings, availability, and host profiles.',
  'Los precios reflejan el precio publicado, no el precio final pagado (impuestos, limpieza, servicio)': 'Prices are advertised rates and exclude taxes, cleaning, and service fees',
  '12.9% de listados sin precio registrado': '12.9% of listings have no recorded price',
  '12.6% sin calificaciones (listados nuevos sin reseñas)': '12.6% have no ratings, including new listings without reviews',
  'Granularidad geográfica: 16 alcaldías (no colonias individuales)': 'Geographic resolution: 16 boroughs, rather than individual neighborhoods',
  'Ofertas totales': 'Total listings',
  'Precio promedio / noche': 'Average nightly price',
  'Calificación promedio': 'Average rating',
  'Disponibilidad mediana': 'Median availability',
  ' días/mes': ' days/month',
  'Distribución de precios': 'Price distribution',
  'Histograma de precio por noche agrupado por tipo de alojamiento.': 'Nightly price distribution by room type.',
  'La mayoría de las ofertas se concentra entre MXN 500 y 2,000/noche. Los alojamientos completos dominan las bandas de precio medio-alto; los cuartos privados se agrupan cerca del piso de MXN 500.': 'Most listings cost MXN 500–2,000 per night. Entire homes dominate the middle and upper price bands; private rooms cluster around MXN 500.',
  'Mapa geográfico': 'Geographic distribution',
  'Ubicación y precio de ~3,000 ofertas representativas en la CDMX.': 'Location and price of approximately 3,000 representative Mexico City listings.',
  'Las ofertas se concentran densamente en Cuauhtémoc (Roma, Condesa, Centro) y Miguel Hidalgo (Polanco, Lomas). Las ofertas de mayor precio (puntos ámbar) bordean el extremo poniente.': 'Listings concentrate in Cuauhtémoc (Roma, Condesa, Centro) and Miguel Hidalgo (Polanco, Lomas). Higher-priced listings cluster toward the western edge.',
  'Ranking por alcaldía': 'Borough comparison',
  'Ofertas, precio promedio y calificación por alcaldía.': 'Listing counts, average prices, and ratings by borough.',
  'Cuauhtémoc concentra el 46% de todas las ofertas, pero Tlalpan y Cuajimalpa muestran los precios promedio más altos con menor volumen — señal de oferta premium en alcaldías periféricas.': 'Cuauhtémoc contains 46% of listings. Tlalpan and Cuajimalpa have fewer listings but the highest average prices, suggesting premium supply in outlying boroughs.',
  'Segmentación de anfitriones': 'Host segmentation',
  'Clasificación de anfitriones por número de listados: casual, profesional y empresarial.': 'Hosts grouped by portfolio size: casual, professional, and business.',
  'Los anfitriones empresariales (6+ ofertas) representan solo el 7% de los anfitriones, pero controlan el 40% de la oferta total. Los anfitriones casuales cobran ligeramente más — los empresariales compiten por volumen.': 'Business hosts with six or more listings represent 7% of hosts but control 40% of supply. Casual hosts charge slightly more; business hosts compete on volume.',
  'Cuarto de hotel': 'Hotel room',
  'Alojamiento entero': 'Entire home',
  'Cuarto privado': 'Private room',
  'Cuarto compartido': 'Shared room',
  '/noche': '/night',
  'anfitriones': 'hosts',
  'ofertas totales': 'total listings',
  'Prom.': 'Avg.',
  'ofertas/anfitrión': 'listings/host',
  'Prom. MXN': 'Avg. MXN',
  'Principales anfitriones:': 'Largest hosts:',
  'Ofertas totales por segmento': 'Total listings by segment',
  'Resumen por segmento': 'Segment summary',
  'Ordenar por': 'Sort by',
  'Ingresos: R$': 'Revenue: R$',
  'Pedidos:': 'Orders:',
  'Precio promedio: R$': 'Average price: R$',
  'Sin datos para los filtros seleccionados': 'No data for the selected filters',
  'Mes 0 = cohorte de adquisición (100%). Los valores posteriores muestran qué % regresó a comprar.': 'Month 0 is the acquisition cohort (100%). Later values show the percentage that purchased again.',
  '— Mes': '— Month',
  '% retención': '% retention',
  'Todos los datos han cargado.': 'All data loaded.',
  'El contenedor está tardando más de lo usual. Reintentando...': 'The data service is taking longer than usual. Retrying…',
  'Consultando 99k órdenes de Olist...': 'Loading Olist order data…',
  'dias': 'days',
  'Dias de entrega': 'Delivery days',
  'Valor prom.: R$': 'Avg. value: R$',
  'Calificación:': 'Rating:',
  'LTV acumulado al mes': 'Cumulative LTV at month',
  'Método: LTV histórico (observado). Alternativas no incluidas: predictivo simple (AOV × frecuencia × vida útil) y probabilístico (BG/NBD + Gamma-Gamma para modelar abandono silencioso en negocios no contractuales).': 'Method: historical observed LTV. Alternatives not included: simple predictive LTV (AOV × frequency × lifetime) and probabilistic models (BG/NBD + Gamma-Gamma for non-contractual customer churn).',
  'Retención de clientes por cohorte, valor de vida del cliente y patrones de entrega en el marketplace más grande de Brasil. Datos de Olist vía Kaggle — 2016 a 2018.': 'Customer cohort retention, lifetime value, and delivery patterns in the Brazilian Olist marketplace. Public Kaggle data, 2016–2018.',
  'Septiembre 2016 a octubre 2018 (25 meses)': 'September 2016 to October 2018 (25 months)',
  '99,441 pedidos entregados de 96,096 clientes únicos': '99,441 delivered orders from 96,096 unique customers',
  'Olist es el marketplace de e-commerce más grande de Brasil, conectando pequeños comerciantes con los principales canales de venta en línea. Este dataset público de Kaggle contiene información real y anonimizada de pedidos: productos, pagos, reseñas, tiempos de entrega y geolocalización de clientes y vendedores.': 'Olist connects small merchants with online sales channels in Brazil. This public Kaggle dataset contains anonymized orders, products, payments, reviews, delivery times, and buyer and seller locations.',
  "Solo pedidos con estatus 'entregado' (excluye cancelados y en proceso)": 'Delivered orders only; cancelled and in-progress orders are excluded',
  'Categorías de producto en portugués (72+ categorías)': 'Product categories retain their Portuguese source names (72+ categories)',
  'Marketplace multi-vendedor — la baja retención es característica del modelo, no un problema de datos': 'Multi-seller marketplace: low retention is characteristic of this model',
  '~13% de pedidos no tienen reseña del cliente': 'Approximately 13% of orders have no customer review',
  'Pedidos totales': 'Total orders',
  'Clientes únicos': 'Unique customers',
  'Valor promedio de pedido': 'Average order value',
  'Días de entrega promedio': 'Average delivery days',
  ' días': ' days',
  'Ingresos mensuales': 'Monthly revenue',
  'Evolución de ingresos y volumen de pedidos a lo largo del tiempo.': 'Revenue and order volume over time.',
  'Los ingresos del marketplace crecieron de forma sostenida entre 2017 y 2018, con picos en noviembre (Black Friday) y un ticket promedio relativamente estable.': 'Marketplace revenue grew steadily during 2017–2018, with November peaks around Black Friday and relatively stable average order values.',
  'Retención por cohorte': 'Cohort retention',
  'Porcentaje de clientes que regresaron a comprar en los meses siguientes a su primera orden.': 'Percentage of customers purchasing again in the months after their first order.',
  'La retención cae drásticamente después del primer mes — menos del 5% de los clientes realiza un segundo pedido en los siguientes 3 meses. Las cohortes de 2017 muestran retención ligeramente superior.': 'Retention drops sharply after the first month: fewer than 5% place a second order within three months. The 2017 cohorts show slightly higher retention.',
  'Valor de vida del cliente': 'Customer lifetime value',
  'LTV histórico: ingreso acumulado total de cada cohorte dividido entre su número de clientes. Si una cohorte muestra R$ 171, significa que el cliente promedio gastó R$ 171 en total desde su primera compra.': 'Historical LTV divides cumulative cohort revenue by its customer count. An LTV of R$171 means that the average customer has spent R$171 since their first purchase.',
  'Las cohortes más grandes generan entre R$150–250 de valor acumulado por cliente. La mayor parte del gasto se concentra en los primeros 2 meses — después la curva se aplana.': 'Larger cohorts generate R$150–250 per customer. Most spending occurs in the first two months, after which the curve flattens.',
  'Categorías principales': 'Leading categories',
  'Top 15 categorías de producto ordenadas por ingreso total.': 'Top 15 product categories ranked by total revenue.',
  'Salud y belleza, relojes y cama/mesa/baño dominan los ingresos. Las categorías de mayor ticket no siempre son las de mayor volumen de pedidos.': 'Health and beauty, watches, and bed/bath products lead revenue. Categories with the highest order values do not always have the highest order counts.',
  'Ventas por estado': 'Sales by state',
  'Distribución geográfica de pedidos, valor promedio y calificación por estado brasileño.': 'Orders, average order value, and review scores by Brazilian state.',
  'São Paulo concentra más del 40% de los pedidos. Los estados del noreste muestran calificaciones de reseña ligeramente menores, correlacionado con tiempos de entrega más largos.': 'São Paulo accounts for more than 40% of orders. Northeastern states have slightly lower review scores, associated with longer delivery times.',
  'Entrega vs. calificación': 'Delivery and review scores',
  'Relación entre tiempo de entrega, calificación promedio y porcentaje de entregas tardías.': 'Relationship between delivery time, average review score, and late deliveries.',
  'Entregas en 0-7 días promedian 4.3 estrellas. A partir de 21 días, la calificación cae por debajo de 3.5 y el porcentaje de entregas tardías supera el 50%.': 'Deliveries within 0–7 days average 4.3 stars. After 21 days, scores fall below 3.5 and more than 50% of deliveries are late.',
  'Segmentación RFM': 'RFM segmentation',
  'Recencia, Frecuencia y Valor Monetario — las tres dimensiones que clasifican a cada cliente por su comportamiento de compra. RFM es más discriminante cuando la frecuencia promedio es >= 2 (negocios con recompra natural: suscripciones, retail, SaaS). En Olist, con ~97% de clientes de compra única, la dimensión F colapsa y la segmentación depende principalmente de R y M.': 'Recency, frequency, and monetary value classify purchasing behavior. RFM is more informative when average frequency is at least two. With approximately 97% one-time customers at Olist, frequency contributes little; segments primarily reflect recency and spend.',
  "La frecuencia promedio de 1.03 pedidos por cliente confirma que Olist opera como un marketplace de compra única — típico de plataformas multi-vendedor donde el cliente no tiene lealtad a Olist sino al producto. Los segmentos 'Alto valor recurrente' y 'Recurrentes estables' (~3% del total) representan a los escasos clientes que regresaron; en ellos se concentra el mayor retorno potencial de campañas de retención. En un negocio con mayor recurrencia, el modelo RFM separaría segmentos más equilibrados y accionables.": 'Average frequency is 1.03 orders per customer. High-value repeat buyers and stable repeat buyers account for approximately 3% of customers, concentrating the potential for retention campaigns. A business with more repeat purchases would produce more balanced, actionable RFM segments.',
  'Filtros': 'Filters',
  'Todas las categorías': 'All categories',
  'Todos los estados': 'All states',
  'Todos los pagos': 'All payment methods',
  'Potencial de recompra': 'Potential repeat buyers',
  'En riesgo de abandono': 'At risk of churn',
  'Compra única': 'One-time buyers',
  'clientes': 'customers',
  'Recencia prom.:': 'Avg. recency:',
  'Frecuencia prom.:': 'Avg. frequency:',
  'Clientes por segmento': 'Customers by segment',
  'Método: RFM clásico con puntuación por cuartiles (1–4) en cada dimensión. Puntuación combinada R+F+M (rango 3–12) asigna segmentos. En contextos con frecuencia promedio': 'Method: classical RFM quartile scores (1–4) for each dimension. The combined R+F+M score (3–12) assigns segments. For average frequency below',
  '2, la variante RFM-T (con Tenure) o modelos probabilísticos como BG/NBD permiten estimar probabilidad de recompra — más apropiado para negocios contractuales o con ciclo de vida definido.': '2, alternatives include RFM-T (with tenure) and probabilistic models such as BG/NBD to estimate repeat-purchase probability; model choice depends on the customer lifecycle.',
  'Acerca de los datos': 'About the data',
  'Fuente:': 'Source:',
  'Periodo:': 'Period:',
  'Registros:': 'Records:',
  'Limitaciones:': 'Limitations:',
  'Filtrar': 'Filter',
  'Ano': 'Year',
  'Diferencia': 'Difference',
  '% Dif': '% difference',
  'Siniestros:': 'Claims:',
  'Rezago de reporte por línea de negocio': 'Reporting lag by line of business',
  'Línea': 'Line',
  'Promedio (días)': 'Average (days)',
  'Mediana (días)': 'Median (days)',
  'Consultando datos de siniestros CAS/NAIC...': 'Loading CAS/NAIC claims data…',
  '100% — Punto de equilibrio': '100% — Break-even',
  'Año:': 'Year:',
  'Frecuencia:': 'Frequency:',
  'Severidad:': 'Severity:',
  'Año de accidente:': 'Accident year:',
  'Observado:': 'Observed:',
  'Triángulos de desarrollo, estimación IBNR y ratios combinados para líneas de negocio de seguros. Datos del Casualty Actuarial Society (CAS) y NAIC -- 1988 a 1997.': 'Development triangles, IBNR estimates, and combined ratios across insurance lines. Casualty Actuarial Society (CAS) and NAIC data, 1988–1997.',
  'Años de accidente 1988 a 1997 (10 años de desarrollo)': 'Accident years 1988–1997 (10 development years)',
  'Triángulos de desarrollo para 6 líneas de negocio de múltiples aseguradoras': 'Development triangles for six lines of business across multiple insurers',
  'La base de datos de reservas del Casualty Actuarial Society (CAS) contiene triángulos de desarrollo extraídos del Schedule P del NAIC. Incluye pérdidas incurridas, pérdidas pagadas, primas devengadas y conteo de siniestros para líneas de negocio como Auto Personal, Workers Comp, Medical Malpractice, Responsabilidad Civil, Responsabilidad de Producto y Auto Comercial.': 'The CAS Loss Reserve Database contains development triangles extracted from NAIC Schedule P: incurred and paid losses, earned premiums, and claim counts for personal auto, workers compensation, medical malpractice, general liability, product liability, and commercial auto.',
  'Datos agregados por línea de negocio y compañía (no siniestros individuales)': 'Data is aggregated by line of business and insurer, not individual claim',
  'Solo incluye aseguradoras que reportan al NAIC (excluye reaseguradoras y cautivas)': 'Only NAIC-reporting insurers are included; reinsurers and captives are excluded',
  'El período 1988-1997 puede no reflejar tendencias actuales del mercado': 'The 1988–1997 period may not reflect current market conditions',
  'Los triángulos asumen desarrollo uniforme dentro de cada lag anual': 'Triangles assume uniform development within each annual lag',
  'Como leer este dashboard': 'How to read this analysis',
  'Secciones del dashboard': 'Analysis sections',
  'Triangulo de desarrollo': 'Development triangle',
  '-- Matriz de perdidas acumuladas por ano de accidente (filas) y lag de desarrollo (columnas). El heatmap muestra la magnitud; las celdas proyectadas incluyen la anotacion de IBNR.': '— Cumulative losses by accident year (rows) and development lag (columns). Projected cells include IBNR annotations.',
  'Waterfall de IBNR': 'IBNR waterfall',
  '-- Descompone el ultimate en tres componentes: perdidas pagadas + reserva de caso + IBNR = ultimate proyectado.': '— Paid losses + case reserves + IBNR = projected ultimate losses.',
  'Frecuencia y severidad': 'Frequency and severity',
  '-- Grafico de doble eje que muestra conteo de siniestros (frecuencia) y costo promedio por siniestro (severidad) por ano de accidente.': '— Claim count (frequency) and average claim cost (severity) by accident year.',
  'Loss ratio por LOB': 'Loss ratio by line of business',
  '-- Ratio de perdidas incurridas sobre prima devengada para cada linea de negocio, con toggle entre reportado y ultimate.': '— Incurred losses divided by earned premiums for each line, with reported and ultimate views.',
  '-- Tendencia del ratio combinado (loss ratio + expense ratio) como area apilada. Debajo de 100% indica rentabilidad.': '— Combined ratio (loss ratio + expense ratio) over time. Values below 100% indicate profitability.',
  'Distribucion de severidad': 'Severity distribution',
  '-- Histograma de montos de siniestros individuales y analisis de rezago de reporte.': '— Claim severity distribution and reporting lag analysis.',
  'Usa los filtros de': 'Use the filters for',
  'linea de negocio (LOB)': 'line of business (LOB)',
  'compania': 'insurer',
  'y': 'and',
  'rango de anos de accidente': 'accident year range',
  'para segmentar el analisis. Los KPIs y graficos se actualizan dinamicamente.': 'to segment the analysis. Metrics and charts update with your selection.',
  'Definiciones clave': 'Key definitions',
  '= Perdidas Incurridas / Prima Devengada. Debajo de 100% indica suscripcion rentable.': '= Incurred losses / earned premiums. Values below 100% indicate underwriting profitability before expenses.',
  '= Loss Ratio + Expense Ratio. Debajo de 100% indica rentabilidad operativa total.': '= Loss ratio + expense ratio. Values below 100% indicate underwriting profitability including expenses.',
  '= Incurred But Not Reported. Reserva para siniestros que ya ocurrieron pero aun no se han reportado o desarrollado completamente.': '= Incurred but not reported: reserves for claims that have occurred but have not yet been reported or fully developed.',
  'proyecta perdidas ultimates multiplicando los valores observados por factores de desarrollo historicos. Es puramente basado en datos.': 'projects ultimate losses by multiplying observed values by historical development factors.',
  'modera la proyeccion combinando los factores de desarrollo con un loss ratio a-priori esperado. Es mas estable para anos de accidente recientes donde hay pocos datos observados.': 'combines development factors with an expected prior loss ratio, stabilizing estimates for recent accident years with limited observations.',
  'Prima neta devengada': 'Net earned premium',
  'Triángulo de desarrollo': 'Development triangle',
  'Pérdidas acumuladas por año de accidente y período de desarrollo. IBNR estimado por diferencia entre último desarrollo observado y factor ultimate.': 'Cumulative losses by accident year and development period. IBNR reflects the difference between observed and projected ultimate losses.',
  'Los años de accidente más recientes muestran mayor incertidumbre en sus estimaciones IBNR debido a menos períodos de desarrollo observados. Los años más maduros (1988-1990) están prácticamente desarrollados al 100%.': 'Recent accident years have greater IBNR uncertainty because fewer development periods are observed. Mature years (1988–1990) are nearly fully developed.',
  'Comparación de estimaciones IBNR por año de accidente entre ambos métodos actuariales.': 'Compare IBNR estimates by accident year for the two actuarial methods.',
  'BF tiende a moderar las estimaciones en años recientes donde CL puede ser volátil por falta de datos observados. Diferencias grandes sugieren que la elección de método impacta materialmente la reserva.': 'BF moderates estimates for recent years where CL can be volatile. Large differences indicate that method choice materially affects the reserve.',
  'Composición del ultimate': 'Ultimate loss composition',
  'Descomposición de la pérdida última por año de accidente: observado + IBNR = Ultimate.': 'Ultimate losses by accident year: observed losses + IBNR = ultimate.',
  'La proporción de IBNR aumenta significativamente en los años de accidente recientes, reflejando la mayor incertidumbre inherente a siniestros aún no reportados. En años maduros, el componente IBNR es mínimo.': 'IBNR represents a larger share of recent accident years, reflecting uncertainty about unreported claims. Its share is minimal in mature years.',
  'Tendencia de frecuencia de siniestros (# siniestros / exposicion) y severidad promedio (costo promedio por siniestro) a lo largo del tiempo.': 'Claim frequency (claims / exposure) and average severity (cost per claim) over time.',
  'Una frecuencia decreciente con severidad creciente sugiere que hay menos siniestros pero de mayor costo unitario -- un patrón común en líneas de responsabilidad civil donde las demandas son menos frecuentes pero los montos de liquidación aumentan con la inflación judicial.': 'Falling frequency with rising severity suggests fewer but more expensive claims, a pattern often seen in liability lines as settlement costs increase.',
  'Loss ratio por línea de negocio': 'Loss ratio by line of business',
  'Ratio de pérdida (pérdidas incurridas / primas devengadas) promedio por línea de negocio. La línea de referencia en 100% marca el punto de equilibrio técnico.': 'Average incurred losses / earned premiums by line. The 100% reference line marks loss-only break-even.',
  'Medical Malpractice y Product Liability consistentemente muestran los loss ratios más altos, reflejando la naturaleza long-tail de estas líneas donde el desarrollo de siniestros se extiende por múltiples años.': 'Medical malpractice and product liability show the highest loss ratios, reflecting the long development periods of these lines.',
  'Tendencia del combined ratio': 'Combined ratio trend',
  'Loss ratio + expense ratio = combined ratio. Por debajo de 100% indica rentabilidad técnica; por encima indica pérdida técnica.': 'Loss ratio + expense ratio = combined ratio. Below 100% indicates underwriting profit; above 100% indicates underwriting loss.',
  'El combined ratio fluctúa alrededor del 100%, indicando que la industria opera cerca del punto de equilibrio técnico. Los años con combined ratio superior al 100% dependen de ingresos de inversión para ser rentables.': 'Combined ratios fluctuate around 100%. Years above 100% require investment income to offset underwriting losses.',
  'Distribución de severidad': 'Severity distribution',
  'Histograma de la severidad de siniestros (escala logarítmica) y resumen del rezago de reporte por línea de negocio.': 'Claim severity on a logarithmic scale and reporting lag by line of business.',
  'La distribución de severidad es fuertemente sesgada a la derecha -- la mayoría de los siniestros son de bajo monto, pero una cola larga de siniestros catastróficos concentra una proporción desproporcionada de las pérdidas totales.': 'Severity is strongly right-skewed: most claims are small, while a long tail of large claims accounts for a disproportionate share of total losses.',
  'Todas las líneas': 'All lines of business',
  'Todas las compañías': 'All insurers',
  'Filas = año de accidente. Columnas = lag de desarrollo. Vista:': 'Rows = accident year. Columns = development lag. View:',
  'pérdidas incurridas acumuladas': 'cumulative incurred losses',
  'pérdidas pagadas acumuladas': 'cumulative paid losses',
  'Año': 'Year',
  'Ver gráfica': 'View chart',
  'Ingresos': 'Revenue',
  'Pedidos': 'Orders',
  'Precio promedio': 'Average price',
  'Calificación': 'Rating',
  'Retención': 'Retention',
  'Resumen': 'Overview',
  'Segmentos': 'Segments',
  'Geografía': 'Geography',
  'Metodología': 'Methodology',
  'Proceso técnico': 'Technical evidence',
  'Secciones del análisis': 'Analysis sections',
  'Cohorte desde': 'Cohort from',
  'hasta': 'to',
  'Cohorte mínima:': 'Minimum cohort:',
  'Segmentos RFM': 'RFM segments',
  'Limpiar filtros': 'Reset filters',
  'Valor del primer pedido': 'First order value',
  'Artículos en el primer pedido': 'Items in first order',
  'Reseña del primer pedido': 'First order review',
  'Primer pedido en fin de semana': 'Weekend first order',
  'Pago: tarjeta de crédito': 'Payment: credit card',
  'Pago: tarjeta de débito': 'Payment: debit card',
  'Categoría: relojes y regalos': 'Category: watches and gifts',
  'Categoría: telefonía': 'Category: telephony',
  'Categoría: artículos del hogar': 'Category: household products',
  'Categoría: salud y belleza': 'Category: health and beauty',
  'Categoría: cómputo': 'Category: computing',
  'Categoría: deportes y ocio': 'Category: sports and leisure',
  'Categoría: muebles y decoración': 'Category: furniture and decor',
  'Categoría: otras': 'Category: other',
  'log₂(odds ratio) — a la derecha, mayor probabilidad de recompra': 'log₂(odds ratio) — rightward means higher repeat-purchase odds',
  '· IC95 [': '· 95% CI [',
  'de quienes llegaron al paso anterior': 'of customers reaching the previous step',
  'Tasa de recompra': 'Repeat-purchase rate',
  'Meses desde la primera compra': 'Months since first purchase',
  'Días promedio de entrega': 'Average delivery days',
  'Estado': 'State',
  'días ·': 'days ·',
  '% recompra': '% repeat purchase',
  'Promedio de cohortes': 'Cohort average',
  'Ningún cohorte cumple los filtros actuales. Baja el tamaño mínimo de cohorte.': 'No cohorts match these filters. Reduce the minimum cohort size.',
  'Porcentaje de clientes de cada cohorte que vuelve a comprar en los meses siguientes': 'Percentage of each cohort purchasing again in subsequent months',
  'Cohorte': 'Cohort',
  '· mes': '· month',
  'menor retención': 'lower retention',
  'mayor': 'higher',
  'pedido': 'order',
  'medio': 'average',
  'Clientes acumulados (de menor a mayor gasto)': 'Cumulative customers (lowest to highest spend)',
  'Días desde la primera compra': 'Days since first purchase',
  'S(t) — aún sin recomprar': 'S(t) — no repeat purchase yet',
  'No se pudieron cargar los datos:': 'Unable to load data:',
  'Cargando datos…': 'Loading data…',
  'Ver datos': 'View data',
  'IC 95%': '95% CI',
  'Cohortes individuales': 'Individual cohorts',
  'Mes': 'Month',
  'Mes 0': 'Month 0',
  'Mes N': 'Month N',
  'Recencia': 'Recency',
  'Frecuencia': 'Frequency',
  'Monto': 'Spend',
  'Clientes': 'Customers',
  'Ingresos totales': 'Total revenue',
  'LTV promedio': 'Average LTV',
  'Reseña': 'Review',
  'Día': 'Day',
  'Cohortes': 'Cohorts',
  'Conversión': 'Conversion',
  'Retención absoluta': 'Absolute retention',
  'Retención relativa': 'Relative retention',
  'Mejor vs. peor cohorte': 'Best and worst cohorts',
  'Mejor cohorte': 'Best cohort',
  'Peor cohorte': 'Worst cohort',
  'Todos': 'All',
  'Alto Valor': 'High value',
  'Leales': 'Loyal',
  'Potenciales': 'Potential',
  'En Riesgo': 'At risk',
  'Perdidos': 'Lost',
  'Nuevos': 'New',
  'Sin mediana': 'No median',
  'Análisis de producto · Olist E-Commerce': 'Product analysis · Olist e-commerce',
  'Por qué sólo el 3% vuelve a comprar': 'Why only 3% purchase again',
  'pedidos entregados y': 'delivered orders and',
  'clientes del marketplace brasileño Olist, entre': 'customers from the Brazilian Olist marketplace, from',
  '. Casi nadie regresa — la pregunta es qué distingue a quienes sí.': '. Few customers return. What distinguishes those who do?',
  'de clientes con 2+ pedidos': 'of customers with two or more orders',
  'Porcentaje de cada cohorte que vuelve a comprar, por mes desde la primera compra': 'Percentage of each cohort purchasing again by month since first purchase',
  'La retención del mes 1 promedia': 'Month-one retention averages',
  'entre las': 'across the',
  'cohortes visibles. No es una curva que decae — es una que nunca empieza: el marketplace adquiere bien y no vuelve a ver al cliente.': 'visible cohorts. The marketplace acquires customers successfully, but very few return after acquisition.',
  'Tendencia mensual de ingresos': 'Monthly revenue trend',
  'Ingresos totales por mes de compra': 'Total revenue by purchase month',
  'El pico llega en': 'Revenue peaks in',
  '. El crecimiento es de adquisición, no de repetición.': '. Growth is driven by acquisition rather than repeat purchases.',
  'Clientes nuevos por cohorte': 'New customers by cohort',
  'Tamaño de cada cohorte en su mes de adquisición': 'Cohort size in its acquisition month',
  'Cada barra es una cohorte cuya retención se lee en el mapa de calor de arriba.': 'Each bar represents a cohort whose retention appears in the heatmap above.',
  'Funnel de recompra': 'Repeat-purchase funnel',
  'Cuántos clientes llegan a un segundo, tercer y cuarto pedido': 'Customers reaching a second, third, and fourth order',
  'La barrera está entera en el primer paso:': 'The main barrier is the first step:',
  'llega a una segunda compra, pero de esos': 'reach a second purchase, and of those',
  'sigue a una tercera. Quien vuelve una vez ya se comporta como otro cliente — ganar la segunda compra es el problema, no retener después.': 'continue to a third. Customers who return once behave differently; earning the second purchase is the key retention challenge.',
  'Qué tan rápido desaparece una cohorte': 'How quickly a cohort disappears',
  'Cada cohorte agrupa a los clientes por el mes de su primera compra. Seguirlas mes a mes separa el efecto de la antigüedad del efecto del calendario: si la retención de todas cae igual de rápido, el problema es el producto, no el momento.': 'Cohorts group customers by first-purchase month. Following them over time separates customer age from calendar effects. Similar declines across cohorts suggest a structural retention issue.',
  'Métrica de retención': 'Retention metric',
  'Las celdas vacías no son ceros: son meses que la cohorte todavía no ha vivido. Una cohorte de': 'Empty cells represent months that a cohort has not yet reached. A cohort from',
  'no puede tener un mes 12 en un dataset que termina ahí, y pintarla como 0% de retención sería inventar una caída.': 'cannot have month 12 in a dataset ending at that point. Displaying 0% would invent a decline.',
  'Curva promedio de retención': 'Average retention curve',
  'Promedio de las cohortes visibles con intervalo de confianza al 95%, sobre las cohortes individuales': 'Visible cohort average with a 95% confidence interval, overlaid on individual cohorts',
  'La columna': 'The',
  'de la tabla cae conforme avanza el mes: el promedio del mes 12 se calcula sobre las cohortes con edad suficiente para tenerlo, no sobre todas. El intervalo mide la dispersión': 'column decreases over time: month 12 includes only cohorts old enough to observe it. The interval measures variation',
  'entre': 'between',
  'cohortes — dice si todas se comportan igual, no cuánto error muestral tiene una sola.': 'cohorts, showing how similarly they behave rather than the sampling error of a single cohort.',
  'Retención acumulada de los meses 1 a 6, contra el promedio': 'Cumulative retention in months 1–6 compared with the average',
  'Sólo compiten las cohortes con los seis meses completos. Sin esa condición la peor cohorte siempre sería la más reciente, que no ha tenido tiempo de retener a nadie — un artefacto del corte del dataset, no un hallazgo.': 'Only cohorts with six complete months are compared. Otherwise the newest cohort would appear worst simply because it has had less observation time.',
  'Elegir cohortes (': 'Choose cohorts (',
  'Supervivencia — segmentar por': 'Survival — group by',
  'Medio de pago': 'Payment method',
  'Curva de supervivencia Kaplan-Meier': 'Kaplan–Meier survival curve',
  'Probabilidad de que un cliente aún NO haya hecho su segunda compra': 'Probability that a customer has not yet made a second purchase',
  'La curva cae': 'The curve falls',
  'en dos años y nunca llega al 50%, así que la mediana de supervivencia no existe — con ~97% de compradores únicos, el evento que mediría casi nunca ocurre. Lo que sí se lee es el': 'over two years and never reaches 50%, so median survival is not observed. Approximately 97% of customers buy only once. The curve does reveal the',
  'ritmo': 'pace',
  ': se pierde 1.23 pp en el primer trimestre y alrededor de 0.6 pp en cada trimestre siguiente. La recompra se desacelera al doble, pero': ': it falls 1.23 percentage points in the first quarter and approximately 0.6 points in each subsequent quarter. Repeat purchasing slows by half but',
  'no se detiene': 'does not stop',
  ': sigue ocurriendo a lo largo de los dos años. Es lo contrario de lo que solía afirmar la versión anterior de este tablero, que daba la probabilidad de retorno por nula después de seis meses; la curva no dice eso. El ensanchamiento del intervalo a partir del día 540 es el conjunto en riesgo adelgazándose, no una recaída.': ': it continues throughout the two years. The curve does not support a zero return probability after six months. Wider intervals after day 540 reflect fewer customers remaining at risk.',
  'Quiénes son los que sí vuelven': 'Who comes back',
  'RFM ordena a los clientes por recencia, frecuencia y monto. Con un 3% de recompra la frecuencia casi no varía, así que lo que la segmentación separa aquí es sobre todo recencia y monto de una única compra — y el segmento «Alto Valor» resulta demasiado pequeño para cargar el negocio.': 'RFM ranks customers by recency, frequency, and spend. With a 3% repeat-purchase rate, frequency varies little: segments mostly separate the recency and value of a single purchase. The high-value segment is too small to sustain the business.',
  'El filtro de segmentos afecta a esta página; el rango de cohortes no, porque la segmentación RFM se calcula sobre el estado final de cada cliente y no por su mes de adquisición.': 'The segment filter applies here. Cohort dates do not: RFM uses each customer’s final state rather than their acquisition month.',
  'Índice de Gini': 'Gini index',
  'concentración de ingresos': 'revenue concentration',
  'Tamaño de cada segmento': 'Segment sizes',
  'Clientes por segmento RFM': 'Customers by RFM segment',
  'La distribución está invertida respecto a lo que RFM suele mostrar.': 'The distribution differs from a typical RFM pattern.',
  'concentra el': 'accounts for',
  'de la base y el': 'of customers and',
  'de los ingresos, mientras que &laquo;Alto Valor&raquo; —el segmento que en otros negocios sostiene la facturación— son': 'of revenue, while the high-value segment represents',
  'y el': 'and',
  'del total. No hay un núcleo fiel que proteger: hay que construirlo.': 'of the total. A loyal core of customers still needs to be built.',
  'Concentración de ingresos': 'Revenue concentration',
  'El 20% que más gasta concentra el': 'The highest-spending 20% accounts for',
  'de los ingresos. Se calcula sobre toda la base, sin el filtro de segmentos: medir la concentración': 'of revenue. This uses all customers without segment filtering; measuring concentration',
  'dentro': 'within',
  'de un segmento sería otra estadística.': 'a segment would answer a different question.',
  'Recencia contra frecuencia; el área de cada marca es el número de clientes en esa celda. Ejes compartidos entre paneles.': 'Recency versus frequency; marker area represents customers in each cell. Panels share axes.',
  'La masa está pegada a la línea de un solo pedido. Es la misma historia del funnel, vista de lado: la frecuencia casi no varía, así que lo que separa a los segmentos es sobre todo la recencia y el monto.': 'Customers cluster along the single-order line. As in the funnel, frequency varies little; recency and spend primarily separate the segments.',
  'Valor de vida por segmento': 'Lifetime value by segment',
  'Ingreso acumulado promedio por cliente desde su primera compra. Eje vertical compartido entre paneles.': 'Average cumulative revenue per customer since first purchase. Panels share the vertical axis.',
  'Varios paneles son un solo punto, y eso es el hallazgo, no un dato faltante: el ingreso acumulado de un cliente sólo cambia en un mes en que vuelve a comprar, así que los dos segmentos más grandes —unos 62,000 clientes, casi todos de una sola compra— no tienen curva que trazar. El LTV de este marketplace es, en la práctica, el valor de la primera compra. Sólo los segmentos pequeños y recurrentes acumulan algo con el tiempo, y el eje compartido muestra cuán poco.': 'Several panels contain a single point because cumulative revenue only changes when a customer buys again. The two largest segments contain approximately 62,000 mostly one-time customers. In practice their LTV equals first-order value. Only small repeat-buyer segments accumulate value over time.',
  'Odds ratios de una regresión logística sobre la probabilidad de una segunda compra, con intervalos al 95%': 'Logistic regression odds ratios for a second purchase, with 95% intervals',
  'De 15 variables,': 'Of 15 variables,',
  'tienen un intervalo que no cruza el cero. La más asociada con volver es': 'have intervals that exclude zero. The strongest positive association is',
  '(OR': '(OR',
  '); la más asociada con no volver es': '); the strongest negative association is',
  '). Son asociaciones sobre datos observacionales — describen a quién conviene buscar, no qué palanca mover.': '). These observational associations help identify customers to investigate; they do not establish causal interventions.',
  'Qué haría con esto': 'Recommended next steps',
  'Tratar la segunda compra como el único objetivo de retención. Todo lo demás en el funnel convierte razonablemente; ese paso no.': 'Make the second purchase the primary retention objective. Later funnel steps convert reasonably well; this step does not.',
  'Concentrar el esfuerzo en el 20% que ya aporta el': 'Focus effort on the 20% already contributing',
  'de los ingresos, en vez de repartirlo sobre una base donde el cliente mediano nunca vuelve.': 'of revenue, given that the median customer does not return.',
  'Usar las variables del primer pedido — valor, reseña, categoría — para decidir a quién contactar, ya que son las únicas señales disponibles antes de que el cliente desaparezca.': 'Use first-order value, review, and category to prioritize outreach: these signals are available before customers disappear.',
  'Brasil no es un solo mercado': 'Brazil contains many different markets',
  'Un país de dimensiones continentales con logística muy desigual. Si la entrega influye en que un cliente vuelva, la señal debería verse entre estados — y se ve, aunque no tan fuerte como sería cómodo.': 'Brazil’s continental scale creates large logistical differences. If delivery influences repeat purchases, an association should appear across states. It does, but the relationship is modest.',
  'Mediana de recompra': 'Median repeat-purchase rate',
  'Correlación entrega–recompra': 'Delivery–repeat purchase correlation',
  'Recompra por estado': 'Repeat purchases by state',
  'Todos los estados, contra la mediana nacional': 'All states compared with the national median',
  'El rango va de': 'The range runs from',
  ') a': ') to',
  ') — pero los extremos son estados pequeños, donde unos pocos clientes mueven el porcentaje varios puntos. La lectura seria está en el gráfico de abajo, que pondera por tamaño.': '). The extremes are small states where a few customers shift percentages materially. The size-weighted chart below provides context.',
  'Comparar estados (': 'Compare states (',
  'Curvas de retención por estado': 'Retention curves by state',
  'Porcentaje de los clientes de cada estado que reaparece, mes a mes': 'Percentage of each state’s customers returning by month',
  'Hasta tres estados a la vez: es el máximo que la paleta distingue de forma fiable para cualquier par, incluida la visión con daltonismo. Las curvas caen todas al mismo sitio — ningún estado retiene de forma estructuralmente distinta, lo que apunta a que el problema no es regional.': 'Compare up to three states at once for reliably distinguishable colors. Curves converge to similar levels, suggesting a retention issue shared across regions.',
  'Tiempo de entrega contra recompra': 'Delivery time versus repeat purchases',
  'Un punto por estado, área proporcional al número de clientes': 'One point per state; area is proportional to customer count',
  'La correlación es': 'The correlation is',
  ' — negativa y en la dirección esperada: donde se entrega más rápido se recompra algo más. ': ' — negative, as expected: faster delivery is associated with slightly more repeat purchases. ',
  ' — demasiado débil para sostener que la entrega explique la recompra. ': ' — too weak to conclude that delivery explains repeat purchasing. ',
  'Con': 'With',
  'estados como unidades de observación esto es una asociación descriptiva; no separa la logística de todo lo demás que distingue a São Paulo del norte del país.': 'states as observational units, this is a descriptive association. It does not isolate logistics from other differences between São Paulo and northern states.',
  'Cómo está calculado': 'How the analysis is calculated',
  'Definiciones, la lógica de cada cálculo, la fuente de los datos y lo que este análisis no puede decir. Todo lo que aparece en los tableros sale de aquí.': 'Definitions, calculations, data sources, and limitations behind the analysis.',
  'Activación': 'Activation',
  'Fuente de datos': 'Data source',
  'De Streamlit a estático': 'From Streamlit to static delivery',
  'Análisis de cohortes': 'Cohort analysis',
  'Una': 'A',
  'cohorte': 'cohort',
  'agrupa a los clientes por el mes de su primera compra. Seguirlas por separado permite distinguir dos cosas que una métrica agregada mezcla: el efecto de la antigüedad del cliente y el efecto del calendario. Si la retención cae igual en todas las cohortes, el problema es estructural; si cae sólo en algunas, hay algo que cambió en ese momento.': 'groups customers by first-purchase month. Tracking cohorts separately distinguishes customer age from calendar effects. Similar retention declines across cohorts suggest a structural issue; differences suggest changes affecting particular periods.',
  'Término': 'Term',
  'Definición': 'Definition',
  'Mes de la primera compra del cliente (YYYY-MM)': 'Customer’s first-purchase month (YYYY-MM)',
  'El mes de adquisición. 100% por definición': 'Acquisition month: 100% by definition',
  'N meses naturales después de la primera compra': 'N calendar months after the first purchase',
  'Retención mes N': 'Month N retention',
  'Clientes de la cohorte que compraron en el mes N, sobre el tamaño de la cohorte': 'Customers purchasing in month N divided by cohort size',
  'Celdas vacías, no ceros.': 'Unobserved cells remain empty.',
  'Una cohorte de': 'A cohort from',
  'no puede tener un mes 12 en un dataset que termina en': 'cannot have month 12 in a dataset ending in',
  '. Aquí esas celdas se dejan en blanco y quedan fuera de los promedios. Es la única diferencia deliberada frente al tablero de Streamlit que este reemplaza: aquel usaba': '. These cells remain blank and are excluded from averages. The former Streamlit dashboard used',
  'y contaba esos meses como 0% de retención, lo que arrastraba la cola de la curva promedio hacia abajo por censura y no por comportamiento. Por eso la curva promedio publica también el número de cohortes que entran en cada punto.': 'and counted unobserved months as 0% retention, artificially lowering the average curve. Each point now also reports the number of observed cohorts contributing to it.',
  'RFM puntúa a cada cliente en tres dimensiones y combina los puntajes en segmentos accionables. Se calcula sobre el estado final de cada cliente, no por su mes de adquisición — razón por la cual el filtro de cohortes no mueve esta página.': 'RFM scores customers on three dimensions and combines scores into segments. It uses each customer’s final state, so the cohort-date filter does not change this page.',
  'Dimensión': 'Dimension',
  'Qué mide': 'Measure',
  'Dirección': 'Direction',
  'Días desde la última compra al corte del dataset': 'Days from the last purchase to the dataset cutoff',
  'Número total de pedidos entregados': 'Total delivered orders',
  'Ingreso total generado por el cliente': 'Total revenue generated by the customer',
  'La frecuencia se rankea antes de cortar en quintiles porque su distribución es casi degenerada: con un 97% de clientes en un solo pedido,': 'Frequency is ranked before dividing into quintiles. With 97% of customers placing one order,',
  'sobre los valores crudos no encuentra cinco cortes distintos y falla. Rankear rompe los empates de forma arbitraria pero estable, que es lo mejor disponible cuando la variable casi no varía — y conviene saberlo al leer los segmentos: la F aporta poca información real en este dataset.': 'cannot find five distinct cut points in the raw values. Ranking breaks ties arbitrarily but consistently. Frequency therefore provides little meaningful differentiation in this dataset.',
  'El estimador Kaplan-Meier responde: ¿cuál es la probabilidad de que un cliente': 'The Kaplan–Meier estimator asks: what is the probability that a customer has',
  'todavía no': 'not yet',
  'haya hecho su segunda compra, t días después de la primera? Es la herramienta correcta aquí porque el dato está': 'made a second purchase t days after the first? It accounts for data that is',
  'censurado por la derecha': 'right-censored',
  ': de un cliente que aún no recompró no sabemos que nunca lo hará, sólo que no lo ha hecho todavía. Tratar esos casos como &laquo;no recompra&raquo; subestimaría la retención de las cohortes recientes.': ': a customer who has not returned may do so later. Treating such cases as permanent non-returners would underestimate recent-cohort retention.',
  'Días de la primera a la segunda compra, o al corte del dataset si no hubo segunda': 'Days from first to second purchase, or to the cutoff if no second purchase is observed',
  '1 si hubo segunda compra, 0 si el caso está censurado': '1 for an observed second purchase; 0 for a censored observation',
  'Probabilidad de no haber recomprado hasta el día t': 'Probability of no repeat purchase by day t',
  'La curva se estima en el pipeline, no en el navegador, y se muestrea en una malla semanal hasta los 720 días. Los intervalos usan la transformación log-log (Greenwood exponencial), que es la que produce': 'The pipeline estimates the curve and samples it weekly through day 720. Intervals use the log-log transformation (exponential Greenwood) provided by',
  'por omisión; la forma directa sobre S(t) puede salirse de [0, 1], que para una probabilidad no es dibujable. El producto se acumula sobre cada tiempo de evento distinto y sólo después se muestrea, porque hacerlo al revés calcularía mal el conjunto en riesgo.': 'by default, keeping probability intervals within [0, 1]. Products are accumulated at each distinct event time before sampling to preserve the correct risk set.',
  'La mediana no existe.': 'The median is not observed.',
  'S(t) se estabiliza cerca del 95% y nunca llega al 50%, así que no hay un día en el que la mitad de los clientes haya recomprado. El tablero informa &laquo;sin mediana&raquo; en lugar de un número: con ~97% de compradores únicos, el evento que la mediana mediría casi nunca ocurre.': 'S(t) stabilizes near 95% and never reaches 50%. The dashboard reports no median because half of customers never reach a second purchase during observation.',
  'Factores de activación': 'Activation factors',
  'Una regresión logística sobre la probabilidad de una segunda compra, usando sólo variables conocidas en el primer pedido: su valor, su reseña, el número de artículos, el medio de pago y la categoría. Los coeficientes se presentan como odds ratios en escala log₂, donde duplicar y reducir a la mitad quedan a la misma distancia del cero.': 'Logistic regression estimates second-purchase odds using first-order value, review, item count, payment method, and category. Odds ratios use a log₂ scale, placing doubled and halved odds equally far from zero.',
  'El gráfico colorea una variable sólo cuando su intervalo al 95% no cruza el cero. Un coeficiente cuyo intervalo incluye &laquo;sin efecto&raquo; no tiene dirección que afirmar, aunque su estimación puntual caiga a un lado. Y todo esto es observacional: las asociaciones describen a quién conviene buscar, no qué pasaría si se cambiara la variable.': 'Color indicates an interval excluding zero on the log₂ scale. Intervals including zero do not establish an effect direction. These observational associations do not predict the causal result of changing a variable.',
  'Muestra pública del marketplace brasileño Olist, publicada en Kaggle: nueve CSV con pedidos anonimizados. Este análisis usa': 'Public Olist marketplace data from Kaggle: nine CSV files of anonymized orders. The analysis uses',
  'pedidos entregados de': 'delivered orders from',
  'clientes únicos, entre': 'unique customers, between',
  ', en': ', across',
  'estados.': 'states.',
  'Métrica': 'Metric',
  ', nunca': ', never',
  'Olist emite un': 'Olist issues a new',
  'nuevo por pedido, así que agrupar por él contaría cada compra como un cliente distinto: inflaría el número de clientes y haría desaparecer la recompra por construcción — el hallazgo central del análisis sería un artefacto de la llave elegida.': 'for every order. Grouping by that identifier would count each purchase as a different customer, inflating customer counts and eliminating repeat purchases by construction.',
  'Este tablero fue una aplicación Streamlit que leía 36 MB de parquet en cada interacción y por eso necesitaba un contenedor corriendo. Sus tres filtros —rango de cohortes, tamaño mínimo de cohorte y segmento RFM— resultaron ser': 'The former Streamlit application read 36 MB of parquet on each interaction. Its cohort range, minimum cohort size, and RFM segment filters only selected',
  'subconjuntos': 'subsets',
  ', nunca recálculos: seleccionan filas de una matriz ya agregada. Nada volvía a calcularse desde los': 'of pre-aggregated rows. No filter required recalculating the original',
  'pedidos.': 'orders.',
  'Así que la misma interactividad sobrevive a un export estático, siempre que el JSON esté preagregado en los ejes por los que cortan los filtros: mes de cohorte, segmento y estado. Los dos conjuntos por cliente (': 'The same interactions work in a static export using JSON aggregated by cohort month, segment, and state. The two customer-level datasets (',
  'filas cada uno) no se publican: el mapa RFM sale como rejilla agrupada y la curva de supervivencia como puntos ya estimados. El resultado son': 'rows each) remain unpublished: RFM uses a grouped grid and survival uses pre-estimated points. The result is',
  'KB de JSON —unos 38 KB comprimidos— en lugar de un servicio con estado.': 'KB of JSON, approximately 38 KB compressed.',
  'Que los números no cambiaran es una afirmación verificable, así que está verificada:': 'Numerical parity is verified by',
  'vuelve a calcular cada cifra desde el parquet con las mismas expresiones que usaban las páginas de Streamlit y las compara con el JSON publicado. La curva Kaplan-Meier y sus dos intervalos se comparan contra': 'which recalculates every figure from parquet using the original expressions and compares them with the published JSON. The Kaplan–Meier curve and intervals are compared with',
  ', la implementación de referencia, en toda la malla.': ', the reference implementation, across the full grid.',
  'Censura.': 'Censoring.',
  'El dataset termina en': 'The dataset ends in',
  '. Las cohortes más recientes han tenido menos tiempo para recomprar, así que su retención observada es un piso, no una estimación.': '. Recent cohorts have less follow-up time, so observed repeat purchasing is a lower bound.',
  'Es un marketplace.': 'Marketplace structure.',
  'Olist es intermediario: la experiencia depende también del vendedor, que este análisis no puede separar de la plataforma.': 'Olist is an intermediary. Customer experience also depends on sellers, whose effects this analysis cannot isolate.',
  'Observacional.': 'Observational evidence.',
  'Ninguna cifra aquí identifica un efecto causal. La correlación entre entrega y recompra se calcula sobre 24 estados como unidades, y São Paulo difiere del norte del país en mucho más que la logística.': 'No result identifies a causal effect. Delivery–repeat purchase correlations use 24 states, which differ in many ways beyond logistics.',
  'Datos faltantes.': 'Missing data.',
  'Cerca del 8% de los pedidos no tiene reseña. Los promedios de reseña y de entrega se calculan sobre los pedidos que sí la tienen, con numerador y denominador propios en lugar de rellenar.': 'Approximately 8% of orders have no review. Review and delivery averages each use their own observed records and denominators rather than filling missing values.',
  'Frecuencia casi constante.': 'Nearly constant frequency.',
  'Con un 97% de clientes de un solo pedido, la F de RFM aporta poca información y los segmentos los separa sobre todo la recencia y el monto.': 'With 97% one-time customers, RFM frequency adds little information. Recency and spend primarily distinguish segments.',
  '01 — Limpieza': '01 — Cleaning',
  'Ingesta y limpieza de datos': 'Data ingestion and cleaning',
  'Nueve CSV unidos en dos tablas analíticas. Aquí se resuelve customer_unique_id contra customer_id, la decisión de la que depende todo lo demás.': 'Nine CSV files joined into two analytical tables. This notebook resolves customer_unique_id versus customer_id, the identifier choice underlying the analysis.',
  '02 — Exploración': '02 — Exploration',
  'Análisis exploratorio': 'Exploratory analysis',
  'Tendencias macro, distribuciones y patrones geográficos. El notebook más pesado: cada figura de Plotly lleva sus datos incrustados.': 'Macro trends, distributions, and geographic patterns. This is the largest notebook because Plotly figures embed their data.',
  '03 — Retención': '03 — Retention',
  'Matrices de retención, curvas de supervivencia y pruebas estadísticas. Produce las matrices que el tablero publica como JSON.': 'Retention matrices, survival curves, and statistical tests. Produces the matrices published as dashboard JSON.',
  'Segmentos, LTV y activación': 'Segments, LTV, and activation',
  'Puntajes RFM, curvas de valor de vida y la regresión logística de la que salen los odds ratios de activación.': 'RFM scores, lifetime value curves, and the logistic regression behind activation odds ratios.',
  'El código detrás de cada cifra': 'The code behind every figure',
  'Los cuatro notebooks completos, tal como se ejecutaron, con su código y sus salidas. Nada de lo que aparece en los tableros sale de un paso que no esté aquí.': 'Four complete notebooks with their original code and outputs document every analytical step.',
  'Abrir aparte': 'Open separately',
  'Los notebooks se exportan con': 'Notebooks are exported with',
  'y se publican tal cual. Traen su propio CSS, por lo que se muestran sobre fondo blanco en ambos temas: es el documento original, no una versión reestilizada para el tablero.': 'and published as original research artifacts. Their own styles and original language are preserved on a white background in both themes.',
};

export function useProjectText() {
  const { locale } = usePreferences()
  return useCallback((source: string): string => {
    if (locale === 'es') return source
    if (projectCopy[source]) return projectCopy[source]
    const monthNames: Record<string, string> = { ene: 'Jan', feb: 'Feb', mar: 'Mar', abr: 'Apr', may: 'May', jun: 'Jun', jul: 'Jul', ago: 'Aug', sep: 'Sep', oct: 'Oct', nov: 'Nov', dic: 'Dec' }
    return source.replace(/^(ene|feb|mar|abr|may|jun|jul|ago|sep|oct|nov|dic) (\d{4})$/, (_, month: string, year: string) => `${monthNames[month]} ${year}`)
  }, [locale])
}
