export type Localized = { en: string; es: string }

export type CaseStudy = {
  id: string
  question: Localized
  title: Localized
  finding: Localized
  contribution: Localized
  evidenceLabel: Localized
  coverage: Localized
  sections: { title: Localized; body: Localized }[]
  decision: Localized
  limitations: Localized[]
  sources: { label: string; href: string }[]
  artifacts: { label: Localized; href: string }[]
  figure: 'development' | 'cohort' | 'experiment' | 'revenue' | 'risk' | 'flow' | 'distribution'
}

const l = (en: string, es: string): Localized => ({ en, es })
const repo = '/research/projects'
const olistSource = { label: 'Olist · Brazilian E-Commerce', href: 'https://www.kaggle.com/datasets/olistbr/brazilian-ecommerce' }

/** Editorial content describes the methods; dated observations live in evidence snapshots. */
export const caseStudies: Record<string, CaseStudy> = {
  insurance: {
    id: 'insurance',
    title: l('Estimating outstanding insurance claim payments', 'Estimar cuánto falta por pagar en siniestros de seguros'),
    question: l('How much remains to be paid, and how sensitive is that estimate to the reserving method?', '¿Cuánto queda por pagar y cuánto depende la estimación del método de reservas?'),
    finding: l('The newest accident years contain the least observed development. Their ultimate cost depends most on the projection assumptions.', 'Los años de accidente más recientes tienen menos desarrollo observado. Su costo último depende más de los supuestos de proyección.'),
    contribution: l('Translate loss triangles into an explanation of unpaid obligations, model sensitivity, and profitability assumptions.', 'Traducir triángulos de desarrollo en una explicación de obligaciones pendientes, sensibilidad del modelo y supuestos de rentabilidad.'),
    evidenceLabel: l('Insurance records and simulated claims', 'Registros de seguros y siniestros simulados'),
    coverage: l('Accident years 1988–1997 · valuation at 31 December 1997 · six lines of business', 'Años de accidente 1988–1997 · valuación al 31 de diciembre de 1997 · seis ramos'),
    figure: 'development',
    sections: [
      { title: l('Read across one accident year', 'Leer un año de accidente de izquierda a derecha'), body: l('A row groups claims from the same accident year. Moving right adds development time, not new accident years. At the valuation date, the missing corner is unobserved future development; it is not zero loss.', 'Una fila agrupa siniestros del mismo año de accidente. Avanzar a la derecha añade tiempo de desarrollo, no nuevos años de accidente. A la fecha de valuación, la esquina vacía es desarrollo futuro no observado; no representa pérdidas de cero.') },
      { title: l('Separate what is paid from what is estimated', 'Separar lo pagado de lo estimado'), body: l('Paid losses are cash already disbursed. Incurred losses include paid amounts and case reserves. Ultimate losses are projected final costs. Ultimate minus paid is the total unpaid reserve; ultimate minus incurred is the additional provision beyond reported losses.', 'Los siniestros pagados son desembolsos realizados. Los incurridos incluyen pagos y reservas de caso. Los últimos son costos finales proyectados. Último menos pagado es la reserva total pendiente; último menos incurrido es la provisión adicional a lo reportado.') },
      { title: l('Compare the assumptions, then the estimates', 'Comparar los supuestos antes que las estimaciones'), body: l('Chain-ladder extends observed development patterns. Bornhuetter–Ferguson combines emergence patterns with an a priori expected loss ratio, giving immature years another anchor. Their difference is model sensitivity, not a confidence interval.', 'Chain-ladder prolonga los patrones de desarrollo observados. Bornhuetter–Ferguson combina esos patrones con una siniestralidad esperada a priori, dando otra referencia a los años inmaduros. La diferencia entre métodos es sensibilidad del modelo, no un intervalo de confianza.') },
    ],
    decision: l('Review the immature years and long-tail lines before using a point estimate for reserve or pricing discussions. Compare methods on the same paid or incurred basis.', 'Revisar los años inmaduros y los ramos de cola larga antes de usar una estimación puntual en discusiones de reservas o tarifas. Comparar métodos sobre la misma base pagada o incurrida.'),
    limitations: [
      l('Claim-level severity, frequency, and reporting delays are synthetic demonstrations calibrated to aggregates; they are not observed policyholder records.', 'La severidad, frecuencia y demora de reporte individuales son demostraciones sintéticas calibradas a agregados; no son registros observados de asegurados.'),
      l('Combined ratios assume a 30% expense ratio. Profitability conclusions change with that assumption; no stochastic reserve interval is estimated.', 'El índice combinado supone un 30% de gastos. Las conclusiones de rentabilidad cambian con ese supuesto; no se estima un intervalo estocástico de reservas.'),
    ],
    sources: [{ label: 'CAS · NAIC Schedule P loss reserving data', href: 'https://www.casact.org/publications-research/research/research-resources/loss-reserving-data-pulled-naic-schedule-p' }],
    artifacts: [{ label: l('Loss triangle notebook', 'Notebook de triángulos'), href: `${repo}/01-insurance-claims-dashboard/notebooks/04_loss_triangles.ipynb` }, { label: l('Executive analysis', 'Análisis ejecutivo'), href: `${repo}/01-insurance-claims-dashboard/reports/executive-summary.md` }],
  },
  ecommerce: {
    id: 'ecommerce',
    title: l('Customer repeat purchases and retention over time', 'Recompra y retención de clientes a lo largo del tiempo'),
    question: l('Does marketplace activity translate into customers who return?', '¿La actividad del marketplace se traduce en clientes que regresan?'),
    finding: l('Acquisition, order value, and repeat purchasing answer different questions. A cohort view makes the second purchase visible.', 'La adquisición, el valor del pedido y la recompra responden preguntas distintas. La vista de cohortes hace visible la segunda compra.'),
    contribution: l('Connect marketplace reporting with customer-level cohort, survival, and segmentation analysis.', 'Conectar reportes del marketplace con análisis de cohortes, supervivencia y segmentación por cliente.'),
    evidenceLabel: l('Olist purchase records', 'Registros de compras de Olist'),
    coverage: l('Olist · 2016–2018 · marketplace and delivered-order cohort views', 'Olist · 2016–2018 · vistas del marketplace y de cohortes de pedidos entregados'),
    figure: 'cohort',
    sections: [
      { title: l('Start with the customer, not the order ID', 'Empezar por el cliente, no por el pedido'), body: l('Assign customers to the month of their first purchase using the persistent customer identifier. Follow that same group over time. More orders in a calendar month can reflect newly acquired customers without demonstrating stronger retention.', 'Asignar cada cliente al mes de su primera compra usando el identificador persistente. Seguir al mismo grupo en el tiempo. Más pedidos en un mes pueden reflejar nuevos clientes sin demostrar una mayor retención.') },
      { title: l('Make the denominator visible', 'Hacer visible el denominador'), body: l('Monthly retention divides returning customers by the original cohort size. A blank future cell means the cohort has not reached that age. Kaplan–Meier analysis accounts for customers whose observation window ends before a second purchase.', 'La retención mensual divide los clientes que regresan entre el tamaño original de la cohorte. Una celda futura vacía significa que la cohorte aún no alcanza esa edad. Kaplan–Meier considera clientes cuya observación termina antes de una segunda compra.') },
      { title: l('Distinguish customer value from basket value', 'Distinguir el valor del cliente del valor de su pedido'), body: l('Cumulative revenue per customer grows with both order count and order value. Compare these separately before interpreting repeat customers as bigger spenders. First-order characteristics can identify groups to study, but an association does not establish an intervention effect.', 'El ingreso acumulado por cliente crece tanto por número de pedidos como por valor del pedido. Compararlos por separado antes de interpretar que quienes regresan gastan más por compra. Las características iniciales identifican grupos a estudiar, pero una asociación no establece el efecto de una intervención.') },
    ],
    decision: l('Frame a second-purchase experiment with a fixed follow-up window. Use the marketplace view to locate operating patterns and the cohort view to evaluate customer behavior.', 'Plantear un experimento de segunda compra con un plazo de seguimiento fijo. Usar la vista del marketplace para localizar patrones operativos y las cohortes para evaluar comportamiento.'),
    limitations: [l('The marketplace and cohort analyses use different populations and aggregation paths. Do not compare headline totals without matching order status, period, customer identity, and revenue definition.', 'Los análisis del marketplace y de cohortes usan poblaciones y agregaciones diferentes. No comparar totales sin igualar estado del pedido, periodo, identidad del cliente y definición de ingresos.'), l('Later cohorts have less follow-up. Geographic and first-order associations are observational, not causal estimates.', 'Las cohortes recientes tienen menos seguimiento. Las asociaciones geográficas y de primera compra son observacionales, no estimaciones causales.')],
    sources: [olistSource],
    artifacts: [{ label: l('Cohort methodology', 'Metodología de cohortes'), href: '/cohorts/metodologia/' }, { label: l('Retention notebook', 'Notebook de retención'), href: '/cohorts/notebooks_html/03_cohort_retention.html' }],
  },
  abtest: {
    id: 'abtest',
    title: l('Evaluating a change in conversion with an A/B test', 'Evaluar un cambio en la conversión con una prueba A/B'),
    question: l('Is the treatment effect large and consistent enough to justify a rollout?', '¿El efecto del tratamiento es suficientemente grande y consistente para justificar un lanzamiento?'),
    finding: l('This constructed experiment demonstrates how an aggregate result can conceal different effects across user groups.', 'Este experimento construido demuestra cómo un resultado agregado puede ocultar efectos distintos entre grupos de usuarios.'),
    contribution: l('Bring effect size, statistical uncertainty, segment checks, and experiment design into one decision process.', 'Integrar tamaño del efecto, incertidumbre estadística, análisis de segmentos y diseño experimental en una decisión.'),
    evidenceLabel: l('Simulated data for A/B testing practice', 'Datos simulados para practicar pruebas A/B'),
    coverage: l('January 2017 base experiment · seeded enrichment modifies conversion outcomes', 'Experimento base de enero de 2017 · enriquecimiento reproducible modifica conversiones'),
    figure: 'experiment',
    sections: [
      { title: l('Estimate a difference, not just a verdict', 'Estimar una diferencia, no solo un veredicto'), body: l('Compare treatment and control conversion rates in percentage points. Read the uncertainty around that difference alongside the minimum improvement worth shipping. A small p-value alone says nothing about implementation cost or commercial relevance.', 'Comparar las conversiones de tratamiento y control en puntos porcentuales. Leer la incertidumbre de esa diferencia junto con la mejora mínima que justificaría el lanzamiento. Un valor p pequeño no explica el costo de implementación ni la relevancia comercial.') },
      { title: l('Check who contributes to the average', 'Revisar quién contribuye al promedio'), body: l('Device and returning-user comparisons illustrate heterogeneous effects. These patterns were deliberately introduced by modifying conversion outcomes and generating synthetic attributes. They demonstrate an analytical workflow, not a recovered finding from the original experiment.', 'Las comparaciones por dispositivo y usuario recurrente ilustran efectos heterogéneos. Estos patrones se introdujeron modificando conversiones y generando atributos sintéticos. Demuestran un proceso analítico, no un hallazgo recuperado del experimento original.') },
      { title: l('Make the next test more decisive', 'Diseñar una siguiente prueba más concluyente'), body: l('Choose a primary metric, a meaningful minimum effect, and a stopping rule before collecting data. Frequentist intervals and Bayesian probabilities describe uncertainty under their respective assumptions; neither removes the need to account for repeated looks and exploratory segments.', 'Elegir una métrica principal, un efecto mínimo relevante y una regla de parada antes de recolectar datos. Los intervalos frecuentistas y las probabilidades bayesianas describen incertidumbre bajo sus supuestos; ninguno elimina el problema de consultas repetidas y segmentos exploratorios.') },
    ],
    decision: l('Use this case to specify a confirmatory experiment. Any segment-specific rollout requires fresh, unmodified evidence and a predeclared decision rule.', 'Usar este caso para especificar un experimento confirmatorio. Un lanzamiento por segmento requiere evidencia nueva sin modificar y una regla de decisión previa.'),
    limitations: [l('Conversion outcomes are changed by the enrichment pipeline. Revenue, device, and other added attributes are synthetic; published treatment effects cannot justify a real product rollout.', 'El pipeline de enriquecimiento cambia las conversiones. Ingresos, dispositivo y otros atributos añadidos son sintéticos; los efectos publicados no justifican un lanzamiento real.'), l('Opposite effects in some segments do not by themselves establish Simpson’s paradox. Exploratory comparisons require multiplicity and interaction checks.', 'Efectos opuestos en algunos segmentos no establecen por sí solos la paradoja de Simpson. Las comparaciones exploratorias requieren revisar multiplicidad e interacciones.')],
    sources: [{ label: 'Udacity · base A/B dataset', href: 'https://www.kaggle.com/datasets/zhangluyuan/ab-testing' }],
    artifacts: [{ label: l('Enrichment pipeline', 'Pipeline de enriquecimiento'), href: `${repo}/03-ab-test-analysis/data-pipeline/03_enrich.py` }, { label: l('Statistical analysis notebook', 'Notebook de análisis estadístico'), href: '/abtest/notebooks_html/03_statistical_analysis.html' }],
  },
  kpi: {
    id: 'kpi',
    title: l('Monthly revenue, customer losses, and business performance', 'Ingresos mensuales, pérdida de clientes y desempeño del negocio'),
    question: l('What changed in recurring revenue, and which changes deserve investigation?', '¿Qué cambió en los ingresos recurrentes y qué cambios merecen investigación?'),
    finding: l('Revenue growth and customer health need separate explanations. A revenue bridge shows the contributors; anomaly baselines identify unusual observations.', 'El crecimiento de ingresos y la salud del cliente requieren explicaciones separadas. Un puente de ingresos muestra contribuciones; las referencias de anomalías identifican observaciones inusuales.'),
    contribution: l('Build a reproducible reporting workflow from generated monthly metrics to explanatory charts and bilingual reports.', 'Construir un proceso reproducible desde métricas mensuales generadas hasta gráficos explicativos y reportes bilingües.'),
    evidenceLabel: l('Simulated data from a fictional business', 'Datos simulados de una empresa ficticia'),
    coverage: l('Fictional NovaCRM · January 2024–December 2025 · monthly metrics and three segments', 'NovaCRM ficticia · enero de 2024–diciembre de 2025 · métricas mensuales y tres segmentos'),
    figure: 'revenue',
    sections: [
      { title: l('Reconcile the revenue movement', 'Conciliar el movimiento de ingresos'), body: l('New business and expansion add recurring revenue; contraction and churn remove it. Read these flows together with the reported balance, and check any reconciliation difference before attributing growth to a single driver.', 'Nuevos clientes y expansión añaden ingresos recurrentes; contracción y cancelaciones los reducen. Leer estos flujos junto con el saldo reportado y revisar cualquier diferencia de conciliación antes de atribuir crecimiento a un solo factor.') },
      { title: l('Ask what “unusual” is measured against', 'Preguntar contra qué se mide lo «inusual»'), body: l('An anomaly is a comparison with a statistical baseline, not a diagnosis. Inspect the metric, reference level, detection method, and period together. A pricing event or product launch can explain an unusual value without making the measurement wrong.', 'Una anomalía es una comparación con una referencia estadística, no un diagnóstico. Revisar juntos la métrica, referencia, método y periodo. Un cambio de precio o lanzamiento puede explicar un valor inusual sin que la medición sea incorrecta.') },
      { title: l('Keep projection separate from observation', 'Separar proyección y observación'), body: l('The forecast extends a short monthly history under a smoothing model. Its band expresses model-based uncertainty, not a commitment. The executive report should carry the same period, segment, and assumptions as the charts used to explain it.', 'El pronóstico extiende una historia mensual corta mediante suavizamiento. Su banda expresa incertidumbre del modelo, no un compromiso. El reporte ejecutivo debe conservar periodo, segmento y supuestos de los gráficos que lo explican.') },
    ],
    decision: l('Use the report to assign an investigation: identify the revenue component, affected segment, and event to verify. Validate alert behavior against the simulator before applying it to operational data.', 'Usar el reporte para asignar una investigación: identificar componente de ingresos, segmento afectado y evento a verificar. Validar alertas contra el simulador antes de aplicarlas a datos operativos.'),
    limitations: [l('The company, customer segments, metrics, and narrative events are generated. They demonstrate reporting behavior, not measured business impact.', 'La empresa, segmentos, métricas y eventos son generados. Demuestran el comportamiento del reporte, no impacto de negocio medido.'), l('A short series limits forecast validation. Health-score weights and alert thresholds are configuration choices, not universal business standards.', 'Una serie corta limita la validación del pronóstico. Los pesos del índice de salud y los umbrales de alerta son decisiones de configuración, no estándares universales.')],
    sources: [{ label: 'NovaCRM · seeded data generator', href: `${repo}/04-executive-kpi-report/data-pipeline/01_generate_saas_data.py` }],
    artifacts: [{ label: l('Data generation notebook', 'Notebook de generación de datos'), href: '/kpi/notebooks_html/01_data_generation.html' }, { label: l('Analytics methods', 'Métodos analíticos'), href: '/kpi/notebooks_html/08_analytics_algorithms.html' }, { label: l('December 2025 executive report · English PDF', 'Informe ejecutivo de diciembre de 2025 · PDF en inglés'), href: `${repo}/04-executive-kpi-report/reports/kpi_report_2025-12_en.pdf` }, { label: l('December 2025 executive report · Spanish PDF', 'Informe ejecutivo de diciembre de 2025 · PDF en español'), href: `${repo}/04-executive-kpi-report/reports/kpi_report_2025-12_es.pdf` }],
  },
  portfolio: {
    id: 'portfolio',
    title: l('Comparing investment portfolio returns and risks', 'Comparar rendimientos y riesgos de un portafolio de inversión'),
    question: l('How does the allocation change historical risk and model-based scenarios?', '¿Cómo cambia la asignación el riesgo histórico y los escenarios del modelo?'),
    finding: l('Return, drawdown, and simulated outcomes describe different aspects of a portfolio. The observation window and model assumptions connect them.', 'Rendimiento, caída desde máximos y resultados simulados describen aspectos distintos del portafolio. El periodo observado y los supuestos del modelo los conectan.'),
    contribution: l('Connect allocation and adjusted price histories with performance attribution, risk diagnostics, and scenario analysis.', 'Conectar asignación e históricos de precios ajustados con atribución del rendimiento, diagnóstico de riesgo y escenarios.'),
    evidenceLabel: l('Historical prices and simulated scenarios', 'Precios históricos y escenarios simulados'),
    coverage: l('Six ETFs and SPY benchmark · selected historical window · API data may refresh', 'Seis ETF y referencia SPY · ventana histórica seleccionada · los datos de la API pueden actualizarse'),
    figure: 'risk',
    sections: [
      { title: l('Start with the path, not the endpoint', 'Empezar por la trayectoria, no por el resultado final'), body: l('Cumulative return shows growth over the selected window. Drawdown measures distance below a previous peak, exposing losses that a final return can hide. Compare the portfolio and benchmark over matching dates before interpreting the difference.', 'El rendimiento acumulado muestra crecimiento en la ventana seleccionada. La caída desde máximos mide la distancia a un máximo previo y revela pérdidas que el resultado final puede ocultar. Comparar portafolio y referencia en las mismas fechas.') },
      { title: l('Diversification depends on joint movement', 'La diversificación depende del movimiento conjunto'), body: l('Weights alone do not describe risk. Correlations determine how asset movements combine, while historical and parametric tail estimates answer different questions. Compare estimates using the same horizon and confidence level.', 'Los pesos no describen por sí solos el riesgo. Las correlaciones determinan cómo se combinan los movimientos, mientras las estimaciones históricas y paramétricas de cola responden preguntas diferentes. Comparar estimaciones con el mismo horizonte y nivel de confianza.') },
      { title: l('Treat the frontier as a model result', 'Tratar la frontera como un resultado del modelo'), body: l('Mean–variance optimization uses estimated returns and covariance to select weights. Monte Carlo paths extend assumed portfolio behavior into possible futures. Neither an optimized allocation nor a simulation median demonstrates what a future portfolio will earn.', 'La optimización media–varianza usa rendimientos y covarianzas estimadas para seleccionar pesos. Las trayectorias Monte Carlo extienden un comportamiento supuesto hacia futuros posibles. Ni la asignación optimizada ni la mediana simulada demuestran lo que se ganará.') },
    ],
    decision: l('Compare sensitivity across historical windows and assumptions before interpreting an allocation. Use the outputs as analytical scenarios, with out-of-sample evaluation needed for an allocation claim.', 'Comparar sensibilidad entre ventanas históricas y supuestos antes de interpretar una asignación. Usar las salidas como escenarios analíticos; una conclusión de asignación requiere evaluación fuera de muestra.'),
    limitations: [l('The implementation assumes frictionless trading and a fixed 4.5% risk-free rate. This is a model parameter, not a statement about current market rates.', 'La implementación supone operaciones sin fricciones y una tasa libre de riesgo fija de 4.5%. Es un parámetro del modelo, no una afirmación sobre tasas actuales.'), l('Simulations operate at portfolio level with model-based return assumptions. Cached or refreshed prices can change results; scenarios are not observed future outcomes.', 'Las simulaciones operan a nivel portafolio con supuestos de rendimiento. Precios almacenados o actualizados pueden cambiar resultados; los escenarios no son resultados futuros observados.')],
    sources: [{ label: 'Yahoo Finance · historical price source', href: 'https://finance.yahoo.com/' }],
    artifacts: [{ label: l('Portfolio construction notebook', 'Notebook de construcción'), href: '/portfolio/notebooks_html/02_portfolio_construction.html' }, { label: l('Simulation and frontier methods', 'Métodos de simulación y frontera'), href: '/portfolio/notebooks_html/05_monte_carlo_frontier.html' }],
  },
  operations: {
    id: 'operations',
    title: l('Service requests and response times in New York City', 'Solicitudes de servicio y tiempos de atención en Nueva York'),
    question: l('Where do request volume and resolution delay intersect?', '¿Dónde coinciden el volumen de solicitudes y la demora de resolución?'),
    finding: l('Prioritization requires both volume and delay, with agency and complaint mix held in view. A ranking alone cannot explain a bottleneck.', 'Priorizar requiere volumen y demora, considerando agencia y tipo de solicitud. Un ranking aislado no explica un cuello de botella.'),
    contribution: l('Turn service-request records into a transparent view of workloads, closure times, due-date coverage, and geographic patterns.', 'Convertir registros de solicitudes en una vista de cargas, tiempos de cierre, cobertura de fechas límite y patrones geográficos.'),
    evidenceLabel: l('New York 311 service records', 'Registros de atención del 311 de Nueva York'),
    coverage: l('NYC 311 · requests created in 2024 · resolution and due-date coverage vary', 'NYC 311 · solicitudes creadas en 2024 · cobertura variable de resolución y fechas límite'),
    figure: 'flow',
    sections: [
      { title: l('Follow the request groups', 'Seguir los grupos de solicitudes'), body: l('The flow diagram groups requests by agency, complaint, and recorded status. Its width represents volume. Status-derived stages describe the available records; they are not a sequence of timestamped handoffs or measured time spent in each stage.', 'El diagrama agrupa solicitudes por agencia, queja y estado registrado. El ancho representa volumen. Las etapas derivadas del estado describen registros disponibles; no son una secuencia de transferencias con marcas de tiempo ni tiempo medido por etapa.') },
      { title: l('Separate completed work from the open queue', 'Separar trabajo cerrado de la cola abierta'), body: l('Resolution time is computed from creation to closure for completed requests. Open requests have no final duration yet. Reading closed-request times without the open queue can make a backlog disappear from the performance discussion.', 'El tiempo de resolución se calcula desde creación hasta cierre para solicitudes terminadas. Las abiertas aún no tienen duración final. Leer tiempos de casos cerrados sin la cola abierta puede ocultar el rezago en la discusión de desempeño.') },
      { title: l('Compare like work before assigning a cause', 'Comparar trabajo similar antes de atribuir una causa'), body: l('Inspect complaint mix, volume, and due-date availability when comparing agencies or boroughs. A compliance percentage only describes records with a defined due date. Long observed delays identify a review candidate, not proof of insufficient staffing.', 'Revisar mezcla de solicitudes, volumen y disponibilidad de fechas límite al comparar agencias o alcaldías. Un porcentaje de cumplimiento solo describe registros con fecha límite definida. Demoras largas identifican un candidato a revisión, no prueban falta de personal.') },
    ],
    decision: l('Select an agency–complaint combination with material volume and delay for a process review. Verify operational context and open-case aging before proposing a staffing change.', 'Seleccionar una combinación agencia–solicitud con volumen y demora relevantes para revisar el proceso. Verificar contexto operativo y antigüedad de casos abiertos antes de proponer cambios de personal.'),
    limitations: [l('Recorded statuses do not reconstruct full case histories. Missing due dates limit the population represented by SLA comparisons.', 'Los estados registrados no reconstruyen historias completas. Las fechas límite ausentes restringen la población representada en comparaciones de cumplimiento.'), l('Open-case overdue classification uses the enrichment run date. Rebuilding the same source later can change compliance results; record the run date when comparing outputs.', 'La clasificación de vencimiento de casos abiertos usa la fecha de ejecución del enriquecimiento. Reconstruir la misma fuente después puede cambiar resultados; registrar la fecha al compararlos.')],
    sources: [{ label: 'NYC Open Data · 311 service requests', href: 'https://data.cityofnewyork.us/resource/erm2-nwe9.json' }],
    artifacts: [{ label: l('SLA analysis notebook', 'Notebook de cumplimiento'), href: '/operations/notebooks_html/03_analisis_sla.html' }, { label: l('Process analysis notebook', 'Notebook de análisis de procesos'), href: '/operations/notebooks_html/04_mineria_procesos.html' }],
  },
  airbnb: {
    id: 'airbnb',
    title: l('Airbnb listings, prices, and hosts in Mexico City', 'Alojamientos, precios y anfitriones de Airbnb en Ciudad de México'),
    question: l('How do location, room type, and host scale shape the visible listing market?', '¿Cómo definen ubicación, tipo de alojamiento y escala del anfitrión el mercado visible?'),
    finding: l('Listing prices and host concentration describe the supply on display. They do not directly measure bookings, occupancy, or realized revenue.', 'Los precios publicados y la concentración de anfitriones describen la oferta visible. No miden directamente reservas, ocupación ni ingresos realizados.'),
    contribution: l('Connect price distributions, borough comparisons, and host portfolios while separating observed supply from unobserved demand.', 'Conectar distribuciones de precios, comparaciones por alcaldía y carteras de anfitriones, separando oferta observada de demanda no observada.'),
    evidenceLabel: l('Airbnb listings in Mexico City', 'Anuncios de Airbnb en Ciudad de México'),
    coverage: l('Mexico City · March 2025 snapshot · borough-level summaries', 'Ciudad de México · corte de marzo de 2025 · resúmenes por alcaldía'),
    figure: 'distribution',
    sections: [
      { title: l('Show the distribution before the average', 'Mostrar la distribución antes del promedio'), body: l('A few expensive listings can move the mean away from the typical listing. Compare distributions within room type and location, and inspect missing-price coverage before ranking boroughs on price.', 'Unos pocos anuncios caros pueden alejar el promedio del anuncio típico. Comparar distribuciones dentro de cada tipo y ubicación, y revisar precios faltantes antes de ordenar alcaldías por precio.') },
      { title: l('Count listings and hosts separately', 'Contar anuncios y anfitriones por separado'), body: l('A host can operate multiple listings. Comparing each host segment’s share of hosts with its share of listings reveals the structure of supply. The map shows locations from a sample; borough totals come from the broader processed listing data.', 'Un anfitrión puede operar varios anuncios. Comparar la proporción de anfitriones con la proporción de anuncios por segmento revela la estructura de oferta. El mapa muestra una muestra de ubicaciones; los totales por alcaldía usan la base procesada más amplia.') },
      { title: l('Treat availability as an ambiguous signal', 'Tratar la disponibilidad como una señal ambigua'), body: l('An unavailable calendar day may be booked or blocked by the host. A high advertised price may reflect room mix rather than stronger demand. These distinctions determine which questions the snapshot can answer and which require booking or longitudinal data.', 'Un día no disponible puede estar reservado o bloqueado por el anfitrión. Un precio publicado alto puede reflejar mezcla de alojamientos y no mayor demanda. Estas diferencias delimitan qué responde el corte y qué requiere reservas o datos longitudinales.') },
    ],
    decision: l('Use the snapshot to describe market composition and select comparable listing groups. Validate any pricing or expansion hypothesis with occupancy, realized prices, and repeated snapshots.', 'Usar el corte para describir composición del mercado y seleccionar grupos comparables. Validar hipótesis de precios o expansión con ocupación, precios realizados y cortes repetidos.'),
    limitations: [l('Price and review fields contain missing values. The geographic scatter is sampled, and location summaries are at borough level.', 'Precios y reseñas contienen valores faltantes. El mapa de puntos es una muestra y los resúmenes geográficos son por alcaldía.'), l('A single listing snapshot cannot establish demand strength, an underserved market, or a causal effect on housing.', 'Un solo corte de anuncios no establece intensidad de demanda, un mercado desatendido ni un efecto causal sobre vivienda.')],
    sources: [{ label: 'Inside Airbnb · source documentation', href: 'https://insideairbnb.com/get-the-data/' }],
    artifacts: [{ label: l('Cleaning and aggregation pipeline', 'Pipeline de limpieza y agregación'), href: `${repo}/00-demo-aestehtics/data-pipeline/airbnb_etl.py` }],
  },
}
